name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-files-added:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: List Files Added
        run: |
          added_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }})
          echo "Files Added:"
          echo "${added_files}"
