name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-modified-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        
    - name: Loop through folders
      run: |
        for dir in $(find ./src/* -type d); do
          echo "Directory: $dir"
          if ! git diff HEAD -- $dir; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
        done

    - name: Loop through folders
      run: |
        for dir in $(find ./src/* -type d); do
          echo "Directory: $dir"
          if ! git diff --quiet [${{ github.event.pull_request.head.ref }}] $dir; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
        done
        
    - name: Check folder modification
      run: |
          # Get the name of the folder you want to check
          FOLDER_NAME="path/to/folder"
          # Get the list of files modified in the pull request
          FILES_MODIFIED=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})
          # Check if the folder is in the list of modified files
          if echo "$FILES_MODIFIED" | grep -q "^$FOLDER_NAME"; then
            echo "Folder $FOLDER_NAME has been modified"
            # do something here, e.g. run tests on the modified files in the folder
          else
            echo "Folder $FOLDER_NAME has not been modified"
          fi
