name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list_files_added:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
      
    - name: List files added
      run: |
        echo "Files added in this pull request:"
        git diff --name-only [${{ github.event.pull_request.head.sha }}]^..[${{ github.event.pull_request.head.sha }}]
