name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-modified-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get modified folders
      run: |
        if git diff --quiet main..[${{ github.event.pull_request.head.ref }}] src/POS.Global; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
          
    - name: Check folder modified
      run: |
        if git diff --quiet ${{ github.event.pull_request.head.ref }} -- src/POS.Global; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
          
    - name: Check folder modified HEAD
      run: |
        if git diff --quiet HEAD -- src/POS.Global; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi

    - name: Get modified folders
      run: |
        if git diff --quiet main..[${{ github.event.pull_request.head.ref }}] src/POS.NorthAmerica; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
          
    - name: Check folder modified
      run: |
        if git diff --quiet ${{ github.event.pull_request.head.ref }} -- src/POS.NorthAmerica; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
          
    - name: Check folder modified HEAD
      run: |
        if git diff --quiet HEAD -- src/POS.NorthAmerica; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
