name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-modified-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get modified folders
      run: |
        if ! git diff --quiet main..HEAD .\src\POS.Global; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
