name: List folders in PR

on: pull_request

jobs:
  check_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        run: echo "$(git diff --name-only main...[${{ github.event.pull_request.head.ref }}]"
      
      - name: Get folder list
        id: folder-list
        run: echo "$(echo ${{ steps.changed-files.outputs.files }} | xargs -I {} dirname {} | sort | uniq)"
        
      - name: Print folder list
        run: echo "${{ steps.folder-list.outputs.folders }}"
