name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-modified-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: ${{ github.event.pull_request.head.sha }}
          
    - name: Get pull request info
      id: pr
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        headers: '{"Accept": "application/vnd.github.v3+json"}'
        
    - name: List files
      run: |
        echo "Files in pull request #${{ github.event.pull_request.number }}:"
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files
          
    - name: get files
      run: |
        files=(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }})
        for file_path in "$files"; do
            echo "Added file: $file_path"
        done
