name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-modified-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get modified folders Global
      run: |
        if ! git diff --quiet main..[${{ github.event.pull_request.head.ref }}] src/POS.Global; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi          

    - name: Get modified folders NA
      run: |
        if ! git diff --quiet main..[${{ github.event.pull_request.head.ref }}] src/POS.NorthAmerica; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi

    - name: Loop through folders
      run: |
        for dir in $(find ./src/* -type d); do
          echo "Directory: $dir"
          # Perform actions on each folder here
          git diff --name-only HEAD^ HEAD > files.txt
          if grep -q "$dir" files.txt; then
            echo "The src folder has been modified."
          else
            echo "The src folder has not been modified."
            exit 1
          fi
        done
