name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-modified-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: ${{ github.event.pull_request.head.sha }}

    - name: List modified files
      run: git diff --name-only [${{ github.event.pull_request.base.sha }}] [${{ github.event.pull_request.head.sha }}]
        
    - name: Loop through folders
      run: |
        for dir in $(find ./src/* -type d); do
          echo "Directory: $dir"
          if ! git diff main...${{ github.event.pull_request.head.sha }}; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
        done
            
    - name: Get modified folders
      run: |
        # Get the base branch name from the pull request
        base_branch=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/refs\/heads\///g')
        
        echo "$base_branch"

        # List the modified folders using find
        folders=$(find ./src -type f -not -path "./.git/*" -not -path "*/$base_branch/*" -exec dirname {} \; | sort | uniq)
        
        # Output the list of modified folders
        echo "$folders"
        
        echo "${{ github.event.pull_request.created_at }}"
          
    - name: Print modified folders
      run: |
          # Retrieve the list of modified folders from the previous step
          folders="${{ steps.modified-folders.outputs.folders }}"

          # Print the list of modified folders
          echo "Modified folders: $folders"
          
    - name: Get Added File Paths
      run: |
          for file_path in "${{ (github.event.pull_request.added) }}"; do
            echo "Added file: $file_path"
          done
          echo "${{ (github.event.pull_request.added) }}"
          
    - name: Determine changed directories
      id: changed_dirs
      run: |
          CHANGED_DIRS=$(git diff --name-only main -- [${{ github.event.pull_request.head.sha }}] | xargs -I {} dirname {})
          echo "$CHANGED_DIRS"

    - name: Run script on changed directories
      run: |
          for dir in ${{ steps.changed_dirs.outputs.dirs }}; do
            echo "Running script in directory $dir"
          done
          
    - name: Get pull request info
      id: pr
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        headers: '{"Accept": "application/vnd.github.v3+json"}'
        
    - name: List files
      run: |
        echo "Files in pull request #${{ github.event.pull_request.number }}:"
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files
