name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-modified-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Loop through folders
      run: |
        for dir in $(find ./src/* -type d); do
          echo "Directory: $dir"
          if ! git diff HEAD -- $dir; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi
        done
        
    - name: Get modified folders
      id: modified-folders
      run: |
          # Get the list of changed files in the pull request
          files=$(git diff --name-only HEAD~1 -- HEAD)

          # Parse the folder names from the file paths
          folders=$(echo "$files" | xargs -n1 dirname | sort -u)

          # Output the list of modified folders
          echo "::set-output name=folders::$folders"
          
    - name: Print modified folders
      run: |
          # Retrieve the list of modified folders from the previous step
          folders="${{ steps.modified-folders.outputs.folders }}"

          # Print the list of modified folders
          echo "Modified folders: $folders"
