name: List Files Added in Pull Request

on:
  pull_request:

jobs:
  list-modified-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get modified folders
      run: |
        if git diff --quiet main..[${{ github.event.pull_request.head.ref }}] src/POS.Global; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi          

    - name: Get modified folders
      run: |
        if git diff --quiet main..[${{ github.event.pull_request.head.ref }}] src/POS.NorthAmerica; then
            echo "Changes were made!"
          else
            echo "No changes were made."
          fi

    - name: Get modified folders
      run: |
        $files = Get-ChildItem -Path ./src -Recurse
        foreach($file in $files)
        {
          if git diff --quiet main..[${{ github.event.pull_request.head.ref }}] $file; then
            echo "Changes were made!"
            ./updateversion.ps1
          else
            echo "No changes were made."
          fi          
        }
