name: Update version number

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Update Version Number
      shell: pwsh
      run: |
        .\updateversion.ps1
        echo git diff --name-only --diff-filter=ACMRTUXB main...[${{ github.event.pull_request.head.ref }}] | grep / | sed 's#/*$##' | sort -u
        git config --global user.email "naresh.mup@gmail.com"
        git config --global user.name "NareshMupparaju"
        git commit -m "Update version number" -a
        git push        
