name: Update version number

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Update Version Number
      shell: pwsh
      run: |
        .\updateversion.ps1
        git diff --name-only main...[${{ github.event.pull_request.head.ref }}] | xargs -n 1 dirname | sort | uniq
        git config --global user.email "naresh.mup@gmail.com"
        git config --global user.name "NareshMupparaju"
        git commit -m "Update version number" -a
        git push        
